name: Automated Testing Pipeline

on: [push, pull_request]

jobs:
  Client-Testing:
    name: Test in ${{ matrix.testMode }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - All
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          lfs: true
          
      - name: Restore Cache
        uses: actions/cache@v2
        with:
          path: /Library
          key: Library
          restore-keys: |
            Library
            
      - name: Run Tests for ${{ matrix.testMode }}
        uses: game-ci/unity-test-runner@v2
        id: tests
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.testMode }} Artifacts
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          checkName: ${{ matrix.testMode }} Test Results
          coverageOptions: 'generateAdditionalMetrics;generateHtmlReport;generateBadgeReport'
          
      - name: Upload Test Results 
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
          
      - name: Upload Code Coverage
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Code Coverage results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.coveragePath }}